#!/usr/bin/env python3
import sys
from lib import args
from lib import db

args = args.getArgs().parse_args()

conn = db.getConnection()

def exitWithMessage(message):
    print(message);
    conn.close();
    sys.exit(1);

def createBlackCard():
    card = dict()
    if args.text == None or args.text == '':
        exitWithMessage('Specify card text for inserted black card (-t)')
    card['text'] = args.text    

    if args.draw < 0:
        exitWithMessage('Draw cannot be less than zero (-d)')
    card['draw'] = args.draw

    if args.pick <= 0:
        exitWithMessage('Pick cannot be less than or equal to zero (-p)')
    card['pick'] = args.pick

    if args.watermark == '' or args.watermark == None:
        exitWithMessage('Watermark cannot be blank (--watermark)')
    card['watermark'] = args.watermark

    return card

def createWhiteCard():
    card = dict()
    if args.text == None or args.text == '':
        exitWithMessage('Specify card text for inserted white card (-t)')
    card['text'] = args.text

    if args.watermark == '':
        exitWithMessage('Cannot have blank watermark (--watermark)')
    card['watermark'] = args.watermark

    return card

def doInsert():
    card = {
        'white': lambda: createWhiteCard(),
        'black': lambda: createBlackCard()
    }[args.cardcolor]()

    print('Are you sure you want to insert ' + args.cardcolor + ' card to card set ' + str(args.cardset) + '?')
    print(str(card))
    choice = input('Y/N? ')
    if choice != 'Y' and choice != 'y':
        print('Exiting...')
        conn.close()
        sys.exit(0)
    
    {
        'white': lambda: db.insertWhiteCards([card], args.cardset, conn),
        'black': lambda: db.insertBlackCards([card], args.cardset, conn)
    }[args.cardcolor]()
    
    conn.commit()
    print('Inserted')

def doDelete():
    {
        'white': lambda: db.deleteWhiteCard(args.id, conn),
        'black': lambda: db.deleteBlackCard(args.id, conn)
    }[args.cardcolor]()
    conn.commit()
    print('Card deleted')

def doExport():
    db.backUpCardSet(args.cardset, args.filename)
    print('Export successful')

def doImport():
    db.restoreCardSet(args.filename)
    print('Import successful')

def doCardsets():
    if args.cardcolor == 'white':
        cards = db.getCardSetWhiteCards(args.cardset, conn)
        for card in cards:
            print("{{ id: {0}, text: {1}, watermark: {2} }}".format(card['id'], card['text'].encode('utf-8'), card['watermark']))
    elif args.cardcolor == 'black':
        cards = db.getCardSetBlackCards(args.cardset, conn)
        for card in cards:
            print("{{ id: {0}, text: {1}, pick: {2}, draw: {3}, watermark: {4}}}".format(card['id'], card['text'].encode('utf-8'), card['pick'], card['draw'], card['watermark']))
    else:
        sets = db.getCardSetList(conn)
        for cardset in sets:
            print(str(cardset))
    

#Because python has no switch
commands = {
    'insert': lambda: doInsert(),
    'delete': lambda: doDelete(),
    'export': lambda: doExport(),
    'import': lambda: doImport(),
    'cardsets': lambda: doCardsets(),
}[args.command]()

conn.close();
